# title of website
title: Icey's World

# description of website
description: byang0571's navigation site

# favicon of website
favicon: "https://icey.live/favicon.png?size=40"

# your website url
url: https://icey.live/

# github profile url
github: "https://github.com/byang0571"

# footer message
footer: © 2023-2023 @byang

# template(theme) of your site, available:
# 1. webstack (http://webstack.cc)
template: webstack

# Google analytics
google_analytics: ""

webstack:
  search:
    enabled: true
    default: baidu
    # 可选的搜索引擎
    engines:
      - baidu
      - bilibili
      - zhihu

content:
  categories:
    - name: 常用推荐
      sites:
        - name: 片库
          description: 看视频的地方-你懂的
          url: https://pian-ku.com/
        - name: Youtube(科学上网)
          description: 全球最大的学习分享平台
          url: https://www.youtube.com/
        - name: Google(科学上网)
          description: 全球最大的UI学习分享平台
          url: https://www.google.com/
     - name: 在线工具
      sites:
        - name: 纪妖
          description: 收集中国古今妖怪
          url: https://www.cbaigui.com/
        - name: AirPano
          description: 全景航拍图片和全景视频拍摄
          url: http://cn.airpano.com/
        - name: PixFix
          description: 修复图片的神奇网站
          url: https://zh.pixfix.com/
        - name: RemoveBG
          description: 在线抠图平台-高清
          url: https://www.remove.bg/
        - name: Magic-Eraser
          description: 在线编辑图片平台
          url: https://magicstudio.com/
        - name: TinyPNG
          description: 在线图片压缩平台
          url: https://tinypng.com/
        - name: Extractor Image
          description: 一键下载网站图片
          url: https://extract.pics/
        - name: RoomGPT
          description: 在线装修AI设计平台
          url: https://www.roomgpt.io/
        - name: Vega AI
          description: 在线AI绘画平台
          url: https://rightbrain.art/
        - name: TinyWow
          description: 在线格式转换平台
          url: https://tinywow.com/
        - name: 简视频
          description: 一个网站搞定视频制作
          url: https://www.aewz.com/
    - name: 摄影图库
      sites:
        - name: Unsplash
          description: Beautiful, free photos.
          url: https://unsplash.com/
        - name: visualhunt
          description: 100% Free High Quality Photos
          url: https://visualhunt.com/
        - name: librestock
          description: 65,084 high quality do-what-ever-you-want stock photos
          url: https://librestock.com/
        - name: pixabay
          description: 可在任何地方使用的免费图片和视频
          url: https://pixabay.com/
        - name: SplitShire
          description: Free Stock Photos and Videos for commercial use.
          url: https://www.splitshire.com/
        - name: StockSnap
          description: Beautiful free stock photos
          url: https://stocksnap.io/
        - name: albumarium
          description: The best place to find & share beautiful images
          url: http://albumarium.com/
        - name: myphotopack
          description: A free photo pack just for you. Every month.
          url: https://myphotopack.com/
        - name: Notaselfie
          description: Photos that happen along the way. You can use the images anyway you like. Have fun!
          url: http://notaselfie.com/
        - name: papers
          description: Wallpapers Every Hour!Hand collected :)
          url: http://papers.co/
        - name: stokpic
          description: Free Stock Photos For Commercial Use
          url: http://stokpic.com/
        - name: 55mm
          description: Use our FREE photos to tell your story!
          url: https://55mm.co/visuals
        - name: thestocks
          description: Use our FREE photos to tell your story!
          url: http://thestocks.im/
        - name: freenaturestock
          description: Exclusive mindblowing freebies for designers and developers
          url: http://freenaturestock.com/
        - name: negativespace
          description: Beautiful, High-Resolution Free Stock Photos
          url: https://negativespace.co/
        - name: gratisography
          description: Free high-resolution pictures you can use on your personal and commercial projects, free of copyright restrictions.
          url: https://gratisography.com/
        - name: imcreator
          description: A curated collection of free web design resources, all for commercial use.
          url: http://imcreator.com/free
        - name: lifeofpix
          description: Free high resolution photography
          url: http://www.lifeofpix.com/
        - name: skitterphoto
          description: Free Stock Photos for Creative Professionals
          url: https://skitterphoto.com/
        - name: mmtstock
          description: Free photos for commercial use
          url: https://mmtstock.com/
        - name: magdeleine
          description: HAND-PICKED FREE PHOTOS FOR YOUR INSPIRATION
          url: https://magdeleine.co/browse/
        - name: jeshoots
          description: New Free Photos & Mockups in to your Inbox!
          url: http://jeshoots.com/
        - name: hdwallpapers
          description: High Definition Wallpapers & Desktop Backgrounds
          url: https://www.hdwallpapers.net
        - name: publicdomainarchive
          description: New 100% Free Stock Photos. Every. Single. Week.
          url: http://publicdomainarchive.com/
