# title of website
title: Icey's World

# description of website
description: byang0571's navigation site

# favicon of website
favicon: "https://github.com/byang0571.png?size=40"

# your website url
url: https://byang0571.github.io/Icey-World/

# github profile url
github: "https://github.com/byang0571"

# footer message
footer: © 2023-2023 @byang0571

# template(theme) of your site, available:
# 1. webstack (http://webstack.cc)
template: webstack

# Google analytics
google_analytics: "G-EXE1PJ8CR2"

webstack:
  search:
    enabled: true
    default: baidu
    # 可选的搜索引擎
    engines:
      - google
      - github
      - weibo
      - baidu
      - bilibili
      - zhihu

content:
  categories:
    - name: 常用推荐
      sites:
        - name: Dribbble
          description: 全球UI设计师作品分享平台。
          url: https://dribbble.com/
        - name: Behance
          description: Adobe旗下的设计师交流平台，来自世界各地的设计师在这里分享自己的作品。
          url: https://behance.net/
        - name: UI中国
          description: 图形交互与界面设计交流、作品展示、学习平台。
          url: http://www.ui.cn/
        - name: 站酷
          description: 中国人气设计师互动平台
          url: http://www.zcool.com.cn/
        - name: Pinterest
          description: 全球美图收藏采集站
          url: https://www.pinterest.com/
        - name: 花瓣
          description: 收集灵感,保存有用的素材
          url: http://huaban.com/
        - name: 优设
          description: 设计师交流学习平台
          url: http://www.uisdc.com/
        - name: Producthunt
          description: 发现新鲜有趣的产品
          url: https://www.producthunt.com/
        - name: Youtube
          description: 全球最大的学习分享平台
          url: https://www.youtube.com/
        - name: Google
          description: 全球最大的UI学习分享平台
          url: https://www.google.com/
        - name: Medium
          description: Read, write and share stories that matter
          url: https://medium.com/
    - name: 界面灵感
      sites:
        - name: 咕噜素材
          description: 质量很高的设计素材网站（推荐）
          url: https://www.gulusucai.com/
        - name: 设计周刊
          description: 最新设计资讯（每天更新）
          url: https://www.shejizhoukan.com/
        - name: 字体仓库
          description: 最全的免费商用字体库
          url: https://www.ziticangku.com/
        - name: 电鸭社区
          description: 国内最早的远程工作社区，也是互联网工作者们的聚集地，非常适合设计开发小伙伴关注
          url: https://eleduck.com/
    - name: 发现产品
      sites:
        - name: NEXT
          description: 不错过任何一个新产品
          url: http://next.36kr.com/posts
        - name: 少数派
          description: 高品质数字消费指南
          url: https://sspai.com/
        - name: 利器
          description: 创造者和他们的工具
          url: http://liqi.io/
        - name: Today
          description: 为身边的新产品喝彩
          url: http://today.itjuzi.com/
        - name: 小众软件
          description: 在这里发现更多有趣的应用
          url: https://faxian.appinn.com/
        - name: Pttrns
          description: Check out the finest collection of design patterns, resources, mobile apps and inspiration
          url: https://www.pttrns.com/
        - name: Collect UI
          description: Daily inspiration collected from daily ui archive and beyond.
          url: http://collectui.com/
        - name: UI uigreat
          description: APP界面截图参考
          url: http://ui.uigreat.com/
        - name: Android Niceties
          description: A collection of screenshots encompassing some of the most beautiful looking Android apps.
          url: http://androidniceties.tumblr.com/
    - name: 摄影图库
      sites:
        - name: Unsplash
          description: Beautiful, free photos.
          url: https://unsplash.com/
        - name: visualhunt
          description: 100% Free High Quality Photos
          url: https://visualhunt.com/
        - name: librestock
          description: 65,084 high quality do-what-ever-you-want stock photos
          url: https://librestock.com/
        - name: pixabay
          description: 可在任何地方使用的免费图片和视频
          url: https://pixabay.com/
        - name: SplitShire
          description: Free Stock Photos and Videos for commercial use.
          url: https://www.splitshire.com/
        - name: StockSnap
          description: Beautiful free stock photos
          url: https://stocksnap.io/
        - name: albumarium
          description: The best place to find & share beautiful images
          url: http://albumarium.com/
        - name: myphotopack
          description: A free photo pack just for you. Every month.
          url: https://myphotopack.com/
        - name: Notaselfie
          description: Photos that happen along the way. You can use the images anyway you like. Have fun!
          url: http://notaselfie.com/
        - name: papers
          description: Wallpapers Every Hour!Hand collected :)
          url: http://papers.co/
        - name: stokpic
          description: Free Stock Photos For Commercial Use
          url: http://stokpic.com/
        - name: 55mm
          description: Use our FREE photos to tell your story!
          url: https://55mm.co/visuals
        - name: thestocks
          description: Use our FREE photos to tell your story!
          url: http://thestocks.im/
        - name: freenaturestock
          description: Exclusive mindblowing freebies for designers and developers
          url: http://freenaturestock.com/
        - name: negativespace
          description: Beautiful, High-Resolution Free Stock Photos
          url: https://negativespace.co/
        - name: gratisography
          description: Free high-resolution pictures you can use on your personal and commercial projects, free of copyright restrictions.
          url: https://gratisography.com/
        - name: imcreator
          description: A curated collection of free web design resources, all for commercial use.
          url: http://imcreator.com/free
        - name: lifeofpix
          description: Free high resolution photography
          url: http://www.lifeofpix.com/
        - name: skitterphoto
          description: Free Stock Photos for Creative Professionals
          url: https://skitterphoto.com/
        - name: mmtstock
          description: Free photos for commercial use
          url: https://mmtstock.com/
        - name: magdeleine
          description: HAND-PICKED FREE PHOTOS FOR YOUR INSPIRATION
          url: https://magdeleine.co/browse/
        - name: jeshoots
          description: New Free Photos & Mockups in to your Inbox!
          url: http://jeshoots.com/
        - name: hdwallpapers
          description: High Definition Wallpapers & Desktop Backgrounds
          url: https://www.hdwallpapers.net
        - name: publicdomainarchive
          description: New 100% Free Stock Photos. Every. Single. Week.
          url: http://publicdomainarchive.com/
    - name: PPT资源
      sites:
        - name: OfficePLUS
          description: OfficePLUS，微软Office官方在线模板网站！
          url: http://www.officeplus.cn/Template/Home.shtml
        - name: 优品PPT
          description: 高质量的模版，而且还有PPT图表，PPT背景图等资源
          url: http://www.ypppt.com/
        - name: PPT+
          description: PPT加直播、录制和分享—PPT+语音内容分享平台
          url: http://www.pptplus.cn/
        - name: PPTMind
          description: 分享高端ppt模板与keynote模板的数字作品交易平台
          url: http://www.pptmind.com/
        - name: tretars
          description: The best free Mockups from the Web
          url: http://www.tretars.com/ppt-templates
        - name: 5百丁
          description: 中国领先的PPT模板共享平台
          url: http://ppt.500d.me/
    - name: 图形创意
      sites:
        - name: photoshop
          description: Photoshop不需要解释
          url: https://www.adobe.com/cn/products/photoshop.html
        - name: Affinity Designer
          description: 专业创意软件
          url: https://affinity.serif.com/
        - name: Illustrator
          description: 矢量图形和插图。
          url: https://www.adobe.com/cn/products/illustrator/
        - name: indesign
          description: 页面设计、布局和出版。
          url: http://www.adobe.com/cn/products/indesign.html
        - name: cinema-4d
          description: Cinema 4D is the perfect package for all 3D artists who want to achieve breathtaking results fast and hassle-free.
          url: https://www.maxon.net/en/products/cinema-4d/overview/
        - name: 3ds-max
          description: 3D modeling, animation, and rendering software
          url: https://www.autodesk.com/products/3ds-max/overview
        - name: Blender
          description: Blender is the free and open source 3D creation suite.
          url: https://www.blender.org/
    - name: 在线工具
      sites:
        - name: tinypng
          description: Optimize your images with a perfect balance in quality and file size.
          url: https://tinypng.com/
        - name: goqr
          description: create QR codes for free (Logo, T-Shirt, vCard, EPS)
          url: http://goqr.me/
        - name: ezgif
          description: simple online GIF maker and toolset for basic animated GIF editing.
          url: https://ezgif.com
        - name: Android 9 patch
          description: Android 9-patch shadow generator fully customizable shadows
          url: http://inloop.github.io/shadow4android/
        - name: screen sizes
          description: Viewport Sizes and Pixel Densities for Popular Devices
          url: http://screensiz.es/
        - name: svgomg
          description: SVG在线压缩平台
          url: https://jakearchibald.github.io/svgomg/
        - name: 稿定抠图
          description: 免费在线抠图软件,图片快速换背景-抠白底图
          url: https://www.gaoding.com
    - name: UED团队
      sites:
        - name: Airbnb Design
          description: Airbnb Design
          url: https://airbnb.design
        - name: Facebook Design
          description: Facebook Design
          url: http://facebook.design/
        - name: Google Design
          description: Google Design
          url: https://design.google/
        - name: eico design
          description: 数字化咨询与产品专家
          url: http://eicodesign.com/
        - name: nice design
          description: nicedesign奈思设计是领先的用户体验设计与互联网品牌建设公司
          url: http://www.niceui.cn/
        - name: 腾讯CDC
          description: 腾讯CDC关注于互联网视觉设计、交互设计、用户研究、前端开发。
          url: http://cdc.tencent.com/
        - name: TGideas
          description: TGideas隶属于腾讯公司互动娱乐业务系统的专业推广类设计团队
          url: http://tgideas.qq.com/
        - name: ISUX
          description: 腾讯社交用户体验设计部
          url: https://isux.tencent.com/
        - name: MXD
          description: 腾讯MIG无线互联网事业群设计团队
          url: http://mxd.tencent.com/
        - name: Aliued
          description: 阿里巴巴国际UED团队
          url: http://www.aliued.com/
        - name: U一点
          description: 阿里巴巴（中国站）用户体验设计部博客U一点设计 UED团队
          url: http://www.aliued.cn/
        - name: 网易uedc
          description: 网易用户体验设计中心（User Experience Design Center）
          url: http://uedc.163.com/
        - name: 百度用户体验中心
          description: 百度用户体验中心
          url: http://ued.baidu.com/
        - name: 京东设计中心
          description: 京东设计中心
          url: http://jdc.jd.com/
        - name: 百度企业产品用户体验中心
          description: 百度企业产品用户体验中心
          url: http://eux.baidu.com/
        - name: 携程设计委员会
          description: 携程设计委员会-Ctrip Design Committee
          url: http://ued.ctrip.com/
