# title of website
title: Icey's World

# description of website
description: byang0571's navigation site

# favicon of website
favicon: "https://icey.live/favicon.png?size=40"

# your website url
url: https://icey.live/

# github profile url
github: "https://github.com/byang0571"

# footer message
footer: © 2023-2023 @byang

# template(theme) of your site, available:
# 1. webstack (http://webstack.cc)
template: webstack

# Google analytics
google_analytics: ""

webstack:
  search:
    enabled: true
    default: baidu
    # 可选的搜索引擎
    engines:
      - baidu
      - bilibili
      - zhihu

content:
  categories:
    - name: 常用推荐
      sites:
        - name: 优酷
          description: 海量正版高清视频在线观看
          url: https://www.youku.com/
        - name: 爱奇艺
          description: 海量正版高清视频在线观看
          url: https://www.iqiyi.com/
        - name: 腾讯视频
          description: 海量正版高清视频在线观看
          url: https://v.qq.com/
        - name: Youtube
          description: 全球最大的学习分享平台
          url: https://www.youtube.com/
        - name: Google
          description: 全球最大的UI学习分享平台
          url: https://www.google.com/
    - name: 界面灵感
      sites:
        - name: 咕噜素材
          description: 质量很高的设计素材网站（推荐）
          url: https://www.gulusucai.com/
        - name: 设计周刊
          description: 最新设计资讯（每天更新）
          url: https://www.shejizhoukan.com/
        - name: 字体仓库
          description: 最全的免费商用字体库
          url: https://www.ziticangku.com/
        - name: 电鸭社区
          description: 国内最早的远程工作社区，也是互联网工作者们的聚集地，非常适合设计开发小伙伴关注
          url: https://eleduck.com/
    - name: 摄影图库
      sites:
        - name: Unsplash
          description: Beautiful, free photos.
          url: https://unsplash.com/
        - name: visualhunt
          description: 100% Free High Quality Photos
          url: https://visualhunt.com/
        - name: librestock
          description: 65,084 high quality do-what-ever-you-want stock photos
          url: https://librestock.com/
        - name: pixabay
          description: 可在任何地方使用的免费图片和视频
          url: https://pixabay.com/
        - name: SplitShire
          description: Free Stock Photos and Videos for commercial use.
          url: https://www.splitshire.com/
        - name: StockSnap
          description: Beautiful free stock photos
          url: https://stocksnap.io/
        - name: albumarium
          description: The best place to find & share beautiful images
          url: http://albumarium.com/
        - name: myphotopack
          description: A free photo pack just for you. Every month.
          url: https://myphotopack.com/
        - name: Notaselfie
          description: Photos that happen along the way. You can use the images anyway you like. Have fun!
          url: http://notaselfie.com/
        - name: papers
          description: Wallpapers Every Hour!Hand collected :)
          url: http://papers.co/
        - name: stokpic
          description: Free Stock Photos For Commercial Use
          url: http://stokpic.com/
        - name: 55mm
          description: Use our FREE photos to tell your story!
          url: https://55mm.co/visuals
        - name: thestocks
          description: Use our FREE photos to tell your story!
          url: http://thestocks.im/
        - name: freenaturestock
          description: Exclusive mindblowing freebies for designers and developers
          url: http://freenaturestock.com/
        - name: negativespace
          description: Beautiful, High-Resolution Free Stock Photos
          url: https://negativespace.co/
        - name: gratisography
          description: Free high-resolution pictures you can use on your personal and commercial projects, free of copyright restrictions.
          url: https://gratisography.com/
        - name: imcreator
          description: A curated collection of free web design resources, all for commercial use.
          url: http://imcreator.com/free
        - name: lifeofpix
          description: Free high resolution photography
          url: http://www.lifeofpix.com/
        - name: skitterphoto
          description: Free Stock Photos for Creative Professionals
          url: https://skitterphoto.com/
        - name: mmtstock
          description: Free photos for commercial use
          url: https://mmtstock.com/
        - name: magdeleine
          description: HAND-PICKED FREE PHOTOS FOR YOUR INSPIRATION
          url: https://magdeleine.co/browse/
        - name: jeshoots
          description: New Free Photos & Mockups in to your Inbox!
          url: http://jeshoots.com/
        - name: hdwallpapers
          description: High Definition Wallpapers & Desktop Backgrounds
          url: https://www.hdwallpapers.net
        - name: publicdomainarchive
          description: New 100% Free Stock Photos. Every. Single. Week.
          url: http://publicdomainarchive.com/
    - name: 在线工具
      sites:
        - name: tinypng
          description: Optimize your images with a perfect balance in quality and file size.
          url: https://tinypng.com/
        - name: goqr
          description: create QR codes for free (Logo, T-Shirt, vCard, EPS)
          url: http://goqr.me/
        - name: ezgif
          description: simple online GIF maker and toolset for basic animated GIF editing.
          url: https://ezgif.com
        - name: Android 9 patch
          description: Android 9-patch shadow generator fully customizable shadows
          url: http://inloop.github.io/shadow4android/
        - name: screen sizes
          description: Viewport Sizes and Pixel Densities for Popular Devices
          url: http://screensiz.es/
        - name: svgomg
          description: SVG在线压缩平台
          url: https://jakearchibald.github.io/svgomg/
        - name: 稿定抠图
          description: 免费在线抠图软件,图片快速换背景-抠白底图
          url: https://www.gaoding.com
